version: "3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"